version: 2
updates:
  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    reviewers:
      - "maintainer"
    assignees:
      - "maintainer"
    labels:
      - "dependencies"
      - "github-actions"
    open-pull-requests-limit: 5

  # Docker dependencies (if Dockerfile exists)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday" 
      time: "09:00"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    reviewers:
      - "maintainer"
    labels:
      - "dependencies"
      - "docker"
    open-pull-requests-limit: 3