# Claude Voice Integration Configuration
# ハイブリッド統合アーキテクチャ - 主設定ファイル

# === Integration Settings ===
integration:
  enabled: true
  mode: "smart"  # minimal, smart, full
  strict_mode: false
  auto_reload_config: true
  
# === Voice Settings ===
voice:
  # Manual trigger settings
  manual:
    mode: "brief"        # brief, detailed, technical
    lines: 25
    model: "auto"        # auto = gemma3:1b → gemma2:2b → phi4-mini → orca-mini
    voice: "Kyoko (Enhanced)"
    
  # Auto-completion settings  
  auto_complete:
    enabled: true
    mode: "brief"
    lines: 15
    model: "auto"        # auto = gemma3:1b → gemma2:2b → phi4-mini → orca-mini
    voice: "Kyoko (Enhanced)"
    
  # Auto-waiting settings
  auto_waiting:
    enabled: true
    mode: "brief" 
    lines: 10
    model: "auto"        # auto = gemma3:1b → gemma2:2b → phi4-mini → orca-mini
    voice: "Kyoko (Enhanced)"

# === Audio System ===
audio:
  system_integration: "osascript"  # direct, osascript, wrapper
  fallback_behavior: "graceful"    # graceful, strict, silent
  max_concurrent_voices: 1
  voice_timeout: 30
  respect_dnd: true
  volume_control: "system"         # system, custom
  speech_rate: 180                 # 遅めの速度で聞き取りやすく (デフォルト: 200)
  
# === AI/LLM Settings ===
llm:
  provider: "ollama"               # ollama, openai, anthropic
  ollama:
    url: "http://localhost:11434"
    timeout: 30
    max_retries: 3
    default_model: "gemma3:1b"         # 最優先: Google Gemma3 1B (高速・軽量)
    fallback_models:                    # フォールバック優先順位
      - "gemma2:2b"                    # 第2候補: Google Gemma2 2B
      - "phi4-mini:latest"             # 第3候補: Microsoft Phi-4 Mini
      - "orca-mini:latest"             # 第4候補: Orca Mini (最終フォールバック)
    
# === Performance ===
performance:
  startup_delay: 0                 # seconds
  cache_enabled: true
  cache_ttl: 300                   # seconds
  background_processing: true
  rate_limiting:
    enabled: true
    max_requests_per_minute: 10
    
# === Logging ===
logging:
  level: "INFO"                    # DEBUG, INFO, WARN, ERROR
  file: "~/.tmux/claude/logs/claude-voice.log"
  max_file_size: "10MB"
  rotate_files: true
  retention_days: 7
  
  # Component-specific logging
  components:
    integration: true
    voice_actions: true
    audio_system: false
    llm_requests: false
    
# === Security ===
security:
  allow_external_commands: false
  sandbox_mode: true
  max_text_length: 5000
  sanitize_input: true
  
# === Experimental Features ===
experimental:
  enabled: true
  features:
    realtime_monitoring: false
    context_awareness: false
    multi_language_support: false
    voice_customization: false
    
# === User Interface ===
ui:
  notifications:
    welcome_message: true
    status_updates: true
    error_reporting: true
    
  tmux_integration:
    status_bar_indicator: true
    key_binding_hints: false
    visual_feedback: true
    
# === Environment Specific ===
environments:
  development:
    debug_mode: true
    verbose_logging: true
    test_mode_enabled: true
    
  production:
    debug_mode: false
    performance_monitoring: true
    error_reporting: true