# Appearance and color settings (tmux 2.9+ style syntax)

set -g status-style                  fg=yellow,bg=white,default
set -wg window-status-style          fg=brightyellow,bg=default,dim
set -wg window-status-current-style  fg=brightred,bg=default,bright
set -g pane-border-style             fg=#44475a
set -g pane-active-border-style      fg=#50fa7b
set -g pane-border-lines             heavy
set -g pane-border-indicators        arrows
set -g window-style                  bg=#1e1e2e
set -g window-active-style           bg=terminal
set -g message-style                 fg=brightred,bg=white
set -g display-panes-active-colour   blue
set -g display-panes-colour          brightred
set -wg clock-mode-colour            green
set -g window-status-bell-style      fg=red,bg=black
set -g window-status-activity-style  fg=white,bg=black
